name: test_db_100325
description: ''
version: 0.1.0
author: strombeck.drew@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: testdb100325
  parentArtefactID: prophecydocs1
  buildSystem: wheel
  author: null
  createdAt: '2025-10-03 13:45:33'
pipelines:
  pipelines/test_db_pipeline_100325:
    name: test_db_pipeline_100325
    description: ''
    author: strombeck.drew@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-10-03 13:45:33'
    datasets:
      inputs:
      - datasets/test_dataset_100325
      outputs:
      - datasets/test_target_100325
    subgraphs: []
    dependencies: {}
datasets:
  datasets/test_dataset_100325:
    name: test_dataset_100325
    description: ''
    author: strombeck.drew@prophecy.io
    createdAt: '2025-10-03 13:47:14'
    mode: batch
    physicalDatasets:
      sharedSpark:
        fabricId: 34091
        datasetType: Database
        description: ''
        author: strombeck.drew@prophecy.io
        createdAt: '2025-10-03 13:47:14'
  datasets/test_target_100325:
    name: test_target_100325
    description: ''
    author: strombeck.drew@prophecy.io
    createdAt: '2025-10-03 13:48:10'
    mode: batch
    physicalDatasets:
      sharedSpark:
        fabricId: 34091
        datasetType: Database
        description: ''
        author: strombeck.drew@prophecy.io
        createdAt: '2025-10-03 13:48:10'
templates: {}
jobs:
  jobs/testjob100325:
    name: testjob100325
    description: ''
    fabricUID: 34091
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/test_db_pipeline_100325
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-10-03 13:48:32'
    author: strombeck.drew@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-10-03 13:45:33'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-10-03T13:45:33.498642Z'
  name: plibMaven
  version: 8.12.3
  id: '1568866268'
  createdAt: '2025-10-03T13:45:33.498642Z'
  type: plibMaven
- modifiedAt: '2025-10-03T13:45:33.498642Z'
  name: plibPypi
  version: 2.1.4
  id: '671826437'
  createdAt: '2025-10-03T13:45:33.498642Z'
  type: plibPypi
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2025-10-03 13:44:59'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.49
    isDefault: true
    author: null
    createdAt: '2025-10-03 13:44:59'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
